/*
  HiCAL WEBSITE CONTENT
  ---------------------
  Most routine updates happen in this file. Edit the text between quotes,
  save, commit, and GitHub Pages republishes the site automatically.
*/

window.HICAL_DATA = {
  lab: {
    name: "HiCAL",
    fullName: "High-Speed Computational Aerodynamics Laboratory",
    statement: "High-fidelity computations and stability analysis for transonic, supersonic and hypersonic flows.",
    introTitle: "Computing the physics of high-speed flows.",
    introText: "HiCAL is a computational fluid dynamics research group in Mechanical and Aerospace Engineering at the University of Colorado Colorado Springs. We use high-fidelity CFD, stability analysis and data driven techniques to understand unsteady compressible-flow phenomena and the mechanisms that govern them.",
    university: "Mechanical & Aerospace Engineering · University of Colorado Colorado Springs",
    email: "alakshmi@uccs.edu",
    scholar: "https://scholar.google.com/citations?user=q24xX7AAAAAJ&hl=en&oi=ao",
    cv: "",
    linkedin: "https://www.linkedin.com/in/anirudh-lakshmi-narasimha-prasad",
    joinText: "HiCAL is building a team of students interested in computational fluid dynamics, high-speed aerodynamics, scientific computing, aeroacoustics, and flow stability. Prospective graduate and undergraduate researchers are encouraged to get in touch through the UCCS Mechanical & Aerospace Engineering department."
  },

  research: [
    {
      number: "01",
      title: "Hypersonics",
      text: "Transition, separated hypersonic boundary layers, disturbance receptivity, and aerothermal loading in flight-relevant high-speed flows.",
      tags: ["DNS", "Mach 6", "Transition"]
    },
    {
      number: "02",
      title: "Shock–Boundary-Layer Interactions",
      text: "Three-dimensional separation, shock motion, vortex dynamics, and aerodynamic loading generated by shock interactions with laminar and transitional boundary layers.",
      tags: ["SWBLI", "I-LES", "Unsteadiness"]
    },
    {
      number: "03",
      title: "Jet Acoustics",
      text: "Flow–acoustic coupling, coherent shear-layer structures, and physics-based control of noise from supersonic rectangular and overexpanded jets.",
      tags: ["Aeroacoustics", "LES", "Flow control"]
    },
    {
      number: "04",
      title: "Hydrodynamic Stability",
      text: "Global and convective instability mechanisms in high-speed shear layers and separated flows using linearized Navier–Stokes analysis and modal analysis.",
      tags: ["Global stability", "SPOD", "NS-MFP"]
    }
  ],

  projects: [
    {
      kicker: "HYPERSONICS",
      title: "How free-stream disturbances reshape hypersonic transition",
      text: "DNS and global stability analysis of a Mach 6 cone–cylinder–flare flow reveal distinct transition pathways under quiet and elevated disturbance environments, with major consequences for separation and aerothermal loading.",
      meta: "DNS · Global stability · Hypersonic transition",
      link: "https://doi.org/10.1017/jfm.2025.10456",
      image: "Hypersonics.png"
    },
    {
      kicker: "SHOCK–BOUNDARY-LAYER INTERACTIONS",
      title: "Three-dimensional dynamics of axisymmetric SWBLI",
      text: "High-fidelity simulations show how an impinging oblique shock drives strongly three-dimensional separation, multiple vortex systems, spectral bands of unsteadiness, and azimuthally varying surface loads over axisymmetric bodies.",
      meta: "I-LES · Shock interactions · 3D separation",
      link: "https://doi.org/10.2514/6.2025-3826",
      image: "AxiSBLI.png"
    },
    {
      kicker: "JET ACOUSTICS AND FLOW CONTROL",
      title: "Controlling the structures that radiate jet noise",
      text: "Small-perturbation plasma forcing reorganizes the three-dimensional shear-layer response of a supersonic rectangular jet, providing a route to alter coherent structures and reduce radiative efficiency without large changes to the mean flow.",
      meta: "LES · Supersonic jets · Aeroacoustics · Flow control",
      link: "https://doi.org/10.1017/jfm.2023.1037",
      image: "Jet_noise.png",
    },
    {
      kicker: "HYDRODYNAMIC STABILITY",
      title: "Finding the instability mechanisms before nonlinear breakdown",
      text: "Linearized Navier–Stokes analysis and modal analysis tools are used to identify receptive frequencies, global modes, instabilities, and coherent structures that show up in high-speed flows.",
      meta: "NS-MFP · Linear analysis",
      link: "https://doi.org/10.2514/1.J064967",
      image: "Stability.png",
    }
  ],

  people: [
    {
      role: "Principal Investigator",
      name: "Anirudh Lakshmi Narasimha Prasad",
      title: "Assistant Professor · Mechanical & Aerospace Engineering · UCCS",
      text: "Computational fluid dynamicist working on hypersonics, shock–boundary-layer interactions, jet acoustics, and hydrodynamic stability. The group combines high-fidelity CFD with stability and modal analysis to connect flow structures to the mechanisms that create them.",
      links: [
        { label: "Google Scholar", href: "https://scholar.google.com/citations?user=q24xX7AAAAAJ&hl=en&oi=ao" },
        { label: "LinkedIn", href: "https://www.linkedin.com/in/anirudh-lakshmi-narasimha-prasad" }
      ],
      image: ""
    }
  ],

  publications: [
    {
      year: "2026",
      title: "Effect of Angle of Attack on the Shockwave-Boundary Layer Interaction Over an Axisymmetric Body",
      authors: "Anirudh Lakshmi Narasimha Prasad and S. Unnikrishnan",
      venue: "AIAA AVIATION Forum",
      doi: "https://doi.org/10.2514/6.2026-4628"
    },
    {
      year: "2026",
      title: "Stability Analysis of Shockwave Laminar Boundary Layer Interaction Over a Cylinder",
      authors: "Anirudh Lakshmi Narasimha Prasad and S. Unnikrishnan",
      venue: "AIAA SciTech Forum",
      doi: "https://doi.org/10.2514/6.2026-2838"
    },
    {
      year: "2025",
      title: "Influence of free stream disturbance on hypersonic boundary layer dynamics over a cone–cylinder–flare",
      authors: "Anirudh Lakshmi Narasimha Prasad, K. P. Sarath and S. Unnikrishnan",
      venue: "Journal of Fluid Mechanics 1016, A55",
      doi: "https://doi.org/10.1017/jfm.2025.10456"
    },
    {
      year: "2025",
      title: "Dynamics of Axisymmetric Shockwave-Boundary Layer Interactions",
      authors: "Anirudh Lakshmi Narasimha Prasad, Niyati Chokshi and S. Unnikrishnan",
      venue: "AIAA AVIATION Forum",
      doi: "https://doi.org/10.2514/6.2025-3826"
    },
    {
      year: "2025",
      title: "Three-Dimensional Linear Analysis of Rectangular Shear Layers to Inform Small-Perturbation-Based Flow Control",
      authors: "Anirudh Lakshmi Narasimha Prasad and S. Unnikrishnan",
      venue: "AIAA Journal 63(1)",
      doi: "https://doi.org/10.2514/1.J064967"
    },
    {
      year: "2025",
      title: "Active control of an overexpanded jet using plasma-based actuators",
      authors: "Anirudh Lakshmi Narasimha Prasad and S. Unnikrishnan",
      venue: "Physical Review Fluids 10, 024602",
      doi: "https://doi.org/10.1103/PhysRevFluids.10.024602"
    },
    {
      year: "2024",
      title: "Noise mitigation in rectangular jets through plasma actuator-based shear layer control",
      authors: "Anirudh Lakshmi Narasimha Prasad and S. Unnikrishnan",
      venue: "Journal of Fluid Mechanics 979, A16",
      doi: "https://doi.org/10.1017/jfm.2023.1037"
    },
    {
      year: "2023",
      title: "Effect of plasma actuator-based control on flow-field and acoustics of supersonic rectangular jets",
      authors: "Anirudh Lakshmi Narasimha Prasad and S. Unnikrishnan",
      venue: "Journal of Fluid Mechanics 964, A11",
      doi: "https://doi.org/10.1017/jfm.2023.354"
    }
  ],

  software: [
    {
      title: "Simulation & analysis",
      text: "HiCAL uses high-fidelity DNS/LES together with linearized Navier–Stokes, global stability, spectral, and modal-analysis tools to interrogate high-speed flow physics.",
      label: "Research methods",
      href: "#research"
    },
    {
      title: "Open research artifacts",
      text: "Code, input decks, meshes, reduced datasets, and reproducibility packages can be linked here as new HiCAL projects are released.",
      label: "Coming as projects launch",
      href: ""
    },
    {
      title: "Publication record",
      text: "The complete publication list and citation record are maintained on Google Scholar.",
      label: "View Google Scholar ↗",
      href: "https://scholar.google.com/citations?user=q24xX7AAAAAJ&hl=en&oi=ao"
    }
  ]
};
